CREATE DATABASE lea_rolpin;
USE lea_rolpin;

CREATE TABLE Production (day TIMESTAMP, nb_plis_heure INT, nb_stack_jour INT);
CREATE TABLE Defaut (id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, lasttime TIMESTAMP, defaut TEXT, debut TIMESTAMP DEFAULT CURRENT_TIMESTAMP, fin TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
